export default {
  CUSTOMERS: 'CUSTOMERS',
  WAREHOUSES: 'WAREHOUSES',
  SERVICES: 'SERVICES',
  WAREHOUSESERVICES: 'WAREHOUSESERVICES',
  CARRIERS: 'CARRIERS',
  STOCKS: 'STOCKS',
  PRODUCTS: 'PRODUCTS',
  PRODUCTCATEGORIES: 'PRODUCTCATEGORIES',
  STOCKACCOUNTMOVEMENTS: 'STOCKACCOUNTMOVEMENTS'
}
